export const INSTRUMENT_CHANGE = 'INSTRUMENT_CHANGE';
export const MASTER_VOLUME_CHANGE = 'MASTER_VOLUME_CHANGE';
export const BASIC_VARIATION_CHANGE = 'BASIC_VARIATION_CHANGE';
export const START_STOP_BUTTON_CLICK = 'START_STOP_BUTTON_CLICK';
export const IF_VARIATION_CHANGE = 'IF_VARIATION_CHANGE';
export const TAP_BUTTON_CLICK = 'TAP_BUTTON_CLICK';
export const PRE_SCALE_CHANGE = 'PRE_SCALE_CHANGE';