export const INSTRUMENT_CHANGE = 'INSTRUMENT_CHANGE';

export const MASTER_VOLUME_CHANGE = 'MASTER_VOLUME_CHANGE';

export const BASIC_VARIATION_CHANGE = 'BASIC_VARIATION_CHANGE';

export const START_STOP_BUTTON_CLICK = 'START_STOP_BUTTON_CLICK';