export const INSTRUMENT_CHANGE = 'INSTRUMENT_CHANGE';
export const MASTER_VOLUME_CHANGE = 'MASTER_VOLUME_CHANGE';
export const BASIC_VARIATION_CHANGE = 'BASIC_VARIATION_CHANGE';
export const START_STOP_BUTTON_CLICK = 'START_STOP_BUTTON_CLICK';
export const IF_VARIATION_CHANGE = 'IF_VARIATION_CHANGE';
export const TAP_BUTTON_CLICK = 'TAP_BUTTON_CLICK';
export const PRE_SCALE_CHANGE = 'PRE_SCALE_CHANGE';
export const STEP_BUTTON_CLICK = 'STEP_BUTTON_CLICK';
export const AUTO_FILL_IN_CHANGE = 'AUTO_FILL_IN_CHANGE';
export const FINE_TEMPO_CHANGE = 'FINE_TEMPO_CHANGE';
export const INSTRUMENT_TRACK_CHANGE = 'INSTRUMENT_TRACK_CHANGE';
export const MODE_CHANGE = 'MODE_CHANGE';
export const TEMPO_CHANGE = 'TEMPO_CHANGE';

export const TICK = 'TICK';
export const BLINK_TICK = 'BLINK_TICK';

export const CLEAR_DOWN = 'CLEAR_DOWN';
export const CLEAR_UP = 'CLEAR_UP';
export const CLEAR_DRAG_START = 'CLEAR_DRAG_START';
export const CLEAR_DRAG_END = 'CLEAR_DRAG_END';
export const CLEAR_DRAG_DROP = 'CLEAR_DRAG_DROP';